#have docs that explicitly say latest supported. 

dependencies:
  build:
    - homebrew:latest
    - maven:3.6.1  # Tried to run yb build was instructed to install oraclejdk. After some debugging, installed adoptopenjdk and things worked locally

build_targets:
  - name: default
    commands:
      - brew install adoptopenjdk
      - mvn compile
      - mvn package
      - mvn install
      - mvn test
    tags:
     channel: experimental

ci:
  builds:
    - name: maven-demo
      build_target: default